/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Main.java
 *
 * Created on Oct 15, 2014, 11:42:33 AM
 */
package hkt.license;

import hkt.license.entity.Key;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;
import org.h2.tools.Server;

/**
 *
 * @author longnt
 */
public class Main extends javax.swing.JFrame {

    /** Creates new form Main */
    private String inputData = "";
    private boolean choiseAllmodule = false;
    private Server server = null;

    public Main() {
        initComponents();
        setLocationRelativeTo(this);
        dcDateStart.setDate(new Date());

        addWindowListener(new WindowAdapter() {

            @Override
            public void windowClosed(WindowEvent e) {
                server.stop();
            }

            @Override
            public void windowOpened(WindowEvent e) {
                try {
                    server = org.h2.tools.Server.createTcpServer(new String[]{
                                "-tcpPort", "9092", "-tcpAllowOthers"});

                    server.start();
                } catch (SQLException ex) {
                }
            }
        });
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        dcDateStart = new com.toedter.calendar.JDateChooser();
        lbKeyMachine = new javax.swing.JLabel();
        txtKeyMachine = new javax.swing.JTextField();
        lbDateStart = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lbKeyActivate = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableModule = new javax.swing.JTable();
        lbEnterprisePartner = new javax.swing.JLabel();
        btnKeyActivate = new javax.swing.JButton();
        txtkeyActivate = new javax.swing.JTextField();
        btnEnetreprisePartner = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        dcDateStart1 = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        lbMessenger = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        dcDateStart.setDateFormatString(org.openide.util.NbBundle.getMessage(Main.class, "PanelShowKeyActivate.dcDateStart.dateFormatString")); // NOI18N
        dcDateStart.setFont(new java.awt.Font("Tahoma", 0, 14));
        dcDateStart.setOpaque(false);

        lbKeyMachine.setText(org.openide.util.NbBundle.getMessage(Main.class, "PanelShowKeyActivate.lbKeyMachine.text")); // NOI18N

        txtKeyMachine.setText(org.openide.util.NbBundle.getMessage(Main.class, "PanelShowKeyActivate.txtKeyMachine.text")); // NOI18N

        lbDateStart.setText(org.openide.util.NbBundle.getMessage(Main.class, "PanelShowKeyActivate.lbDateStart.text")); // NOI18N

        jLabel3.setText(org.openide.util.NbBundle.getMessage(Main.class, "PanelShowKeyActivate.jLabel3.text")); // NOI18N

        lbKeyActivate.setText(org.openide.util.NbBundle.getMessage(Main.class, "PanelShowKeyActivate.lbKeyActivate.text")); // NOI18N

        tableModule.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Module"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableModule);

        lbEnterprisePartner.setText(org.openide.util.NbBundle.getMessage(Main.class, "PanelShowKeyActivate.lbEnterprisePartner.text")); // NOI18N

        btnKeyActivate.setFont(new java.awt.Font("Tahoma", 1, 18));
        btnKeyActivate.setText(org.openide.util.NbBundle.getMessage(Main.class, "PanelShowKeyActivate.btnKeyActivate.text")); // NOI18N
        btnKeyActivate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeyActivateActionPerformed(evt);
            }
        });

        txtkeyActivate.setEditable(false);
        txtkeyActivate.setText(org.openide.util.NbBundle.getMessage(Main.class, "PanelShowKeyActivate.txtkeyActivate.text")); // NOI18N

        btnEnetreprisePartner.setText(org.openide.util.NbBundle.getMessage(Main.class, "PanelShowKeyActivate.btnEnetreprisePartner.text")); // NOI18N
        btnEnetreprisePartner.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnEnetreprisePartner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnetreprisePartnerActionPerformed(evt);
            }
        });

        jButton1.setText(org.openide.util.NbBundle.getMessage(Main.class, "PanelShowKeyActivate.jButton1.text")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText(org.openide.util.NbBundle.getMessage(Main.class, "PanelShowKeyActivate.jButton2.text")); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Admin");

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("User");

        dcDateStart1.setDateFormatString(org.openide.util.NbBundle.getMessage(Main.class, "PanelShowKeyActivate.dcDateStart.dateFormatString")); // NOI18N
        dcDateStart1.setFont(new java.awt.Font("Tahoma", 0, 14));
        dcDateStart1.setOpaque(false);

        jLabel1.setText("Đến ngày");

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setText("Máy chủ");

        buttonGroup1.add(jRadioButton4);
        jRadioButton4.setSelected(true);
        jRadioButton4.setText("User");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbDateStart, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbEnterprisePartner, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbKeyMachine, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 431, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnEnetreprisePartner))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 702, Short.MAX_VALUE)
                            .addComponent(txtKeyMachine, javax.swing.GroupLayout.DEFAULT_SIZE, 702, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(dcDateStart, javax.swing.GroupLayout.DEFAULT_SIZE, 331, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dcDateStart1, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jRadioButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jRadioButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lbKeyActivate, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(txtkeyActivate, javax.swing.GroupLayout.DEFAULT_SIZE, 838, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(btnKeyActivate, javax.swing.GroupLayout.DEFAULT_SIZE, 925, Short.MAX_VALUE)))
                .addGap(10, 10, 10))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbEnterprisePartner)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(btnEnetreprisePartner)))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(lbKeyMachine))
                    .addComponent(txtKeyMachine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lbDateStart))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(dcDateStart, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE))
                    .addComponent(dcDateStart1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton3)
                    .addComponent(jRadioButton4))
                .addGap(18, 18, 18)
                .addComponent(btnKeyActivate, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(lbKeyActivate))
                    .addComponent(txtkeyActivate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {dcDateStart, dcDateStart1});

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel7.setForeground(new java.awt.Color(0, 0, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText(org.openide.util.NbBundle.getMessage(Main.class, "PanelShowKeyActivate.jLabel7.text")); // NOI18N

        lbMessenger.setText(org.openide.util.NbBundle.getMessage(Main.class, "PanelShowKeyActivate.lbMessenger.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbMessenger, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 955, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbMessenger, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
     */
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        dcDateStart = new com.toedter.calendar.JDateChooser();
        lbKeyMachine = new javax.swing.JLabel();
        txtKeyMachine = new javax.swing.JTextField();
        lbDateStart = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lbKeyActivate = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableModule = new javax.swing.JTable();
        lbEnterprisePartner = new javax.swing.JLabel();
        btnKeyActivate = new javax.swing.JButton();
        txtkeyActivate = new javax.swing.JTextField();
        btnEnetreprisePartner = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        dcDateStart1 = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        lbMessenger = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        dcDateStart.setDateFormatString("dd/MM/yyyy"); // NOI18N
        dcDateStart.setFont(new java.awt.Font("Tahoma", 0, 14));
        dcDateStart.setOpaque(false);

        lbKeyMachine.setText("Key Machine"); // NOI18N

        txtKeyMachine.setText(""); // NOI18N

        lbDateStart.setText("Từ ngày"); // NOI18N

        jLabel3.setText("DS Module cấp key"); // NOI18N

        lbKeyActivate.setText("Key Activate"); // NOI18N

        tableModule.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{},
                new String[]{
                    "Module"
                }) {

            boolean[] canEdit = new boolean[]{
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableModule);

        lbEnterprisePartner.setText("Khách hàng"); // NOI18N

        btnKeyActivate.setFont(new java.awt.Font("Tahoma", 1, 18));
        btnKeyActivate.setText("Sinh Key Activte"); // NOI18N
        btnKeyActivate.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeyActivateActionPerformed(evt);
            }
        });

        txtkeyActivate.setEditable(false);
        txtkeyActivate.setText(""); // NOI18N

        btnEnetreprisePartner.setText("Danh sách key khách hàng"); // NOI18N
        btnEnetreprisePartner.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnEnetreprisePartner.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnetreprisePartnerActionPerformed(evt);
            }
        });

        jButton1.setText("Tất cả module"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Chọn moudle"); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Admin");

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("User");
        jRadioButton2.setSelected(true);

        dcDateStart1.setDateFormatString("dd/MM/yyyy"); // NOI18N
        dcDateStart1.setFont(new java.awt.Font("Tahoma", 0, 14));
        dcDateStart1.setOpaque(false);

        jLabel1.setText("Đến ngày");

        buttonGroup2.add(jRadioButton3);
        jRadioButton3.setText("Máy chủ");
        buttonGroup2.add(jRadioButton4);
        jRadioButton4.setSelected(true);
        jRadioButton4.setText("Máy trạm");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).
                addGroup(jPanel1Layout.createSequentialGroup().
                addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).
                addGroup(jPanel1Layout.createSequentialGroup().addGap(10, 10, 10).
                addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).
                addComponent(lbDateStart, javax.swing.GroupLayout.PREFERRED_SIZE, 93,
                javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(jButton2).
                addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 93,
                javax.swing.GroupLayout.PREFERRED_SIZE).
                addComponent(lbEnterprisePartner, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(lbKeyMachine, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(jButton1)).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup().addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 431, Short.MAX_VALUE).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(btnEnetreprisePartner)).addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 702, Short.MAX_VALUE).addComponent(txtKeyMachine, javax.swing.GroupLayout.DEFAULT_SIZE, 702, Short.MAX_VALUE).addGroup(jPanel1Layout.createSequentialGroup().addComponent(dcDateStart, javax.swing.GroupLayout.DEFAULT_SIZE, 331, Short.MAX_VALUE).addGap(18, 18, 18).addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(dcDateStart1, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE)).addGroup(jPanel1Layout.createSequentialGroup().addComponent(jRadioButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(jRadioButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)).addGroup(jPanel1Layout.createSequentialGroup().addComponent(jRadioButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(jRadioButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))).addGroup(jPanel1Layout.createSequentialGroup().addGap(10, 10, 10).addComponent(lbKeyActivate, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE).addGap(4, 4, 4).addComponent(txtkeyActivate, javax.swing.GroupLayout.DEFAULT_SIZE, 838, Short.MAX_VALUE)).addGroup(jPanel1Layout.createSequentialGroup().addGap(20, 20, 20).addComponent(btnKeyActivate, javax.swing.GroupLayout.DEFAULT_SIZE, 925, Short.MAX_VALUE))).addGap(10, 10, 10)));
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(jPanel1Layout.createSequentialGroup().addGap(11, 11, 11).addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(jPanel1Layout.createSequentialGroup().addGap(3, 3, 3).addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(lbEnterprisePartner).addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))).addGroup(jPanel1Layout.createSequentialGroup().addGap(1, 1, 1).addComponent(btnEnetreprisePartner))).addGap(11, 11, 11).addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(jPanel1Layout.createSequentialGroup().addGap(3, 3, 3).addComponent(lbKeyMachine)).addComponent(txtKeyMachine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)).addGap(11, 11, 11).addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(jPanel1Layout.createSequentialGroup().addComponent(jLabel3).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(jButton1).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(jButton2)).addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(jPanel1Layout.createSequentialGroup().addGap(10, 10, 10).addComponent(lbDateStart)).addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false).addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE).addComponent(dcDateStart, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)).addComponent(dcDateStart1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED).addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jRadioButton1).addComponent(jRadioButton2)).addGap(11, 11, 11).addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jRadioButton3).addComponent(jRadioButton4)).addGap(18, 18, 18).addComponent(btnKeyActivate, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE).addGap(37, 37, 37).addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(jPanel1Layout.createSequentialGroup().addGap(3, 3, 3).addComponent(lbKeyActivate)).addComponent(txtkeyActivate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)).addGap(12, 12, 12)));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel7.setForeground(new java.awt.Color(0, 0, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Sinh key cài đặt cho khách hàng"); // NOI18N

        lbMessenger.setText(""); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup().addContainerGap().addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING).addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE).addComponent(lbMessenger, javax.swing.GroupLayout.Alignment.LEADING).addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 955, Short.MAX_VALUE)).addContainerGap()));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup().addContainerGap().addComponent(jLabel7).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED).addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED).addComponent(lbMessenger, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)));
        pack();
    }
private void btnKeyActivateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeyActivateActionPerformed
    txtkeyActivate.setText(getKeyActivate());
    Key key = new Key(jTextField1.getText(), txtKeyMachine.getText(), inputData, txtkeyActivate.getText(), dcDateStart.getDate(), dcDateStart1.getDate());
    AccessData.getInstance().insert(key);

}//GEN-LAST:event_btnKeyActivateActionPerformed

private void btnEnetreprisePartnerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnetreprisePartnerActionPerformed
    DialogList d = new DialogList();
    d.setVisible(true);
}//GEN-LAST:event_btnEnetreprisePartnerActionPerformed

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    DefaultTableModel tableModelDelete = (DefaultTableModel) tableModule.getModel();
    Vector v = new Vector();
    v.add("Bán hàng");
    tableModelDelete.addRow(v);

    Vector v6 = new Vector();
    v6.add("Quản lý kho");
    tableModelDelete.addRow(v6);


    Vector v1 = new Vector();
    v1.add("Khuyến mãi");
    tableModelDelete.addRow(v1);

    Vector v5 = new Vector();
    v5.add("Menu Voucher");
    tableModelDelete.addRow(v5);

    Vector v2 = new Vector();
    v2.add("Điểm, Trả trước");
    tableModelDelete.addRow(v2);

    Vector v4 = new Vector();
    v4.add("Thống kê");
    tableModelDelete.addRow(v4);
    choiseAllmodule = true;
}//GEN-LAST:event_jButton1ActionPerformed

private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    choiseAllmodule = false;
    DialogChoiseModule dialog = new DialogChoiseModule();
    dialog.setTableModelDeleteRight((DefaultTableModel) tableModule.getModel());
    dialog.setVisible(true);
    if (dialog.getTableModelDeleteRight() != null) {
        tableModule.setModel(dialog.getTableModelDeleteRight());
    }
}//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Main().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnetreprisePartner;
    private javax.swing.JButton btnKeyActivate;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private com.toedter.calendar.JDateChooser dcDateStart;
    private com.toedter.calendar.JDateChooser dcDateStart1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lbDateStart;
    private javax.swing.JLabel lbEnterprisePartner;
    private javax.swing.JLabel lbKeyActivate;
    private javax.swing.JLabel lbKeyMachine;
    private javax.swing.JLabel lbMessenger;
    private javax.swing.JTable tableModule;
    private javax.swing.JTextField txtKeyMachine;
    private javax.swing.JTextField txtkeyActivate;
    // End of variables declaration//GEN-END:variables

    private String getKeyActivate() {
        try {
            if (jRadioButton1.isSelected()) {
                inputData = "A";
            } else {
                inputData = "U";
            }
            if (jRadioButton3.isSelected()) {
                inputData += "C";
            } else {
                inputData += "T";
            }

            DateFormat df = new SimpleDateFormat("ddMMyy");
            inputData += df.format(dcDateStart.getDate());
            if (dcDateStart1.getDate() == null) {
                inputData += "      ";
            } else {
                String stringNumber = df.format(dcDateStart1.getDate());
                inputData += stringNumber;
            }
            if (choiseAllmodule) {
                inputData += "A";
            } else {
                for (int i = 0; i < tableModule.getRowCount(); i++) {
                    String str = tableModule.getValueAt(i, 0).toString().substring(0, 1);
                    inputData += "/" + str;
                }
            }
            System.out.println(inputData);
            EncryptAES eaes = new EncryptAES(txtKeyMachine.getText(), inputData);
            return eaes.encrypt();
        } catch (Exception ex) {
            ex.printStackTrace();
            return "";
        }
    }
}
